version: "3"
services:
  app:
    container_name: softlab-shop-app
    build: .
    image: softlab-shop-app
    ports:
      - "3003:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
  mongo:
    container_name: softlab-shop-mongo
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
